[provider]
cluster = "localnet"
wallet = "./tests/test-key.json"

[programs.mainnet]
namespaces = "nameXpT2PwZ2iA6DTNYTotTmiMYusBCYqwBLN2QgF4w"

[programs.devnet]
namespaces = "nameXpT2PwZ2iA6DTNYTotTmiMYusBCYqwBLN2QgF4w"

[programs.testnet]
namespaces = "nameXpT2PwZ2iA6DTNYTotTmiMYusBCYqwBLN2QgF4w"

[programs.localnet]
namespaces = "nameXpT2PwZ2iA6DTNYTotTmiMYusBCYqwBLN2QgF4w"
