anchor_version = "0.20.1"
solana_version = "1.9.13"

[scripts]
test = "yarn mocha tests/**/*.spec.ts"

[provider]
cluster = "localnet"
wallet = "./tests/test-key.json"

[programs.mainnet]
cardinal_namespaces = "nameXpT2PwZ2iA6DTNYTotTmiMYusBCYqwBLN2QgF4w"

[programs.devnet]
cardinal_namespaces = "nameXpT2PwZ2iA6DTNYTotTmiMYusBCYqwBLN2QgF4w"

[programs.testnet]
cardinal_namespaces = "nameXpT2PwZ2iA6DTNYTotTmiMYusBCYqwBLN2QgF4w"

[programs.localnet]
cardinal_namespaces = "nameXpT2PwZ2iA6DTNYTotTmiMYusBCYqwBLN2QgF4w"
